# spring-dotenv: localizacao do arquivo .env
dotenv.directory=../
# ===== Aplicacao =====
spring.application.name=ponto

# ===== Banco de Dados (MariaDB) =====
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===== JPA / Hibernate =====
# validate = confere se entities batem com o banco, mas NUNCA altera a estrutura
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true